data = [
    {
        "survived" : 0,
        "pclass": 3,
        "sex": "male",
        "age": 22,
        "sibsp": 1, 
        "parch": 0,
        "fare": 7.25,
        "embarked": "S",
        "class": "Third",
        "alive": "no"}, 
    {
        "survived" : 1,
        "pclass": 1,
        "sex": "female",
        "age": 38,
        "sibsp": 1, 
        "parch": 0,
        "fare": 71.28,
        "embarked": "C",
        "class": "First",
        "alive": "yes"}, 
    {
        "survived" : 1,
        "pclass": 1,
        "sex": "female",
        "age": 38,
        "sibsp": 1, 
        "parch": 0,
        "fare": 71.28,
        "embarked": "C",
        "class": "First",
        "alive": "yes"}, 
    {
        "survived" : 0,
        "pclass": 3,
        "sex": "male",
        "age": 22,
        "sibsp": 1, 
        "parch": 0,
        "fare": 7.25,
        "embarked": "S",
        "class": "Third",
        "alive": "no"}, 
    {
        "survived" : 1,
        "pclass": 1,
        "sex": "female",
        "age": 38,
        "sibsp": 1, 
        "parch": 0,
        "fare": 71.28,
        "embarked": "C",
        "class": "First",
        "alive": "yes"}, 
    {
        "survived" : 1,
        "pclass": 1,
        "sex": "female",
        "age": 38,
        "sibsp": 1, 
        "parch": 0,
        "fare": 71.28,
        "embarked": "C",
        "class": "First",
        "alive": "yes"}, 
    {
        "survived" : 0,
        "pclass": 3,
        "sex": "male",
        "age": 22,
        "sibsp": 1, 
        "parch": 0,
        "fare": 7.25,
        "embarked": "S",
        "class": "Third",
        "alive": "no"}, 
]